id: A1D374215
title: A Discourse on the Confession of Harmful Deeds Spoken by Yama Dharmarāja to
  Karma Chakme
type: translation
pechas:
- I82B7D84E
- I7FFD7379
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:31.067204
  last_modified_at: 2023-01-04 12:45:31.067223
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I82B7D84E/250F: E00C
  I7FFD7379/B999: E00C
